export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST'
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS'
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE'

export const FIND_PRODUCTS_REQUEST = 'FIND_PRODUCT_BY_CATEGORY_REQUEST'
export const FIND_PRODUCTS_SUCCESS = 'FIND_PRODUCT_BY_CATEGORY_SUCCESS'
export const FIND_PRODUCTS_FAILURE = 'FIND_PRODUCT_BY_CATEGORY_FAILURE'


export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'

export const CREATE_PRODUCTS_REQUEST = 'CREATE_PRODUCTS_REQUEST'
export const CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS'
export const CREATE_PRODUCTS_FAILURE = 'CREATE_PRODUCTS_FAILURE'

export const UPDATE_PRODUCTS_REQUEST = 'UPDATE_PRODUCTS_REQUEST'
export const UPDATE_PRODUCTS_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS'
export const UPDATE_PRODUCTS_FAILURE = 'UPDATE_PRODUCTS_FAILURE'

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"



