server:
  port: 6789

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/novatech
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Nvanlinh1!@#
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect

outbound:
  identity:
    client-id: "${client-id}"
    client-secret: "${client-secret}"
    redirect-uri: "${redirect-uri}"

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

frontend:
  url: "http://localhost:5173"
