spring:
  application:
    name: novatech
  datasource:
    url: jdbc:mysql://localhost:3306/novatech
    username: root
    password: Nvanlinh1!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liuBVNTuRGUzqRvD
            client-secret: 609df68aec899ed3499c512168b012abbfe3a3d5
            scope:
              - user:email
              - read:user
          # google:
          #   client-id: Ov23liuBVNTuRGUzqRvD
          #   client-secret: 609df68aec899ed3499c512168b012abbfe3a3d5

frontend:
  url: http://localhost:5173
 
  # mail:
  #     host: smtp.gmail.com
  #     port: 587
  #     username: novatech.shopmobile1@gmail.com
  #     password: zkitnqiojumktiev
  #     properties:
  #       mail:
  #         smtp:
  #           auth: true
  #           starttls: true



server:
  port: 6789

jwt:
  signerKey: "ZQx9jdCwmkSQSrOmwz9mspRjlOZyHZqGmnHgnegvjFn7S1dHu6W11uIFsCHo/m74"


