spring:
  application:
    name: novatech
  datasource:
    url: jdbc:mysql://localhost:3306/novatech
    username: root
    password: Nvanlinh1!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 6789

jwt:
  signerKey: "ZQx9jdCwmkSQSrOmwz9mspRjlOZyHZqGmnHgnegvjFn7S1dHu6W11uIFsCHo/m74"


