version: '3'
services:
  mysql:
    image: mysql:8.0.39-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: novatech
    ports:
      - "3307:3306"
    networks:
      - novatech_network
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./novatech_be
    ports:
      - "6789:6789"
    networks:
      - novatech_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/novatech
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on: 
      - mysql
  
  frontend:
    build: ./novatech_fe
    networks:
      - novatech_network
    ports:
      - "5173:80"

networks:
  novatech_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local