export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE'

export const GET_HISTORY_ORDER_REQUEST = 'GET_HISTORY_ORDER_REQUEST'
export const GET_HISTORY_ORDER_SUCCESS = 'GET_HISTORY_ORDER_SUCCESS'
export const GET_HISTORY_ORDER_FAILURE = 'GET_HISTORY_ORDER_FAILURE'