export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'

export const CREATE_PRODUCTS_REQUEST = 'CREATE_PRODUCTS_REQUEST'
export const CREATE_PRODUCTS_SUCCESS = 'CREATE_PRODUCTS_SUCCESS'
export const CREATE_PRODUCTS_FAILURE = 'CREATE_PRODUCTS_FAILURE'

export const UPDATE_PRODUCTS_REQUEST = 'UPDATE_PRODUCTS_REQUEST'
export const UPDATE_PRODUCTS_SUCCESS = 'UPDATE_PRODUCTS_SUCCESS'
export const UPDATE_PRODUCTS_FAILURE = 'UPDATE_PRODUCTS_FAILURE'

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE'


